  const SEED_REASONS = [
    "Your smile","Your laugh","Your eyes","Your grin","Your eyebrows","Your teeth","Your lips","Your nose",
    "Your hair styled","Your hands (PLEASE TAKE BETTER CARE)","Your smirk","Your style","Your humor",
    "Your dedication","Your patience","The way you call me hubby","The way you say good morning",
    "Whenever you tell me to eat well","Your presence","Your comfort","Whenever you hmm","Whenever u sing",
    "Your cute moles","Your face 😍","Ehem mochi and dango hehe","Your stomach ehem ehem",
    "How you care for people who mean so much to you especially your dad","How hard you work for us",
    "Your maturity","Your immaturity lol","Your sleepy voice when u wake up",
    "Whenever you welcome me back or when im going out","The way you say ni-","Your drawings",
    "Your silly poses and pictures","How you respect me and my choices","How you support me in everything i do",
    "Your movie/show recommendations","How you cherish what people give you","How strong you are mentally",
    "I love calling you my girlfriend","I love calling you my wife","How you talk about our future",
    "YOUR DANCING LOL I STILL REMEMBER HAHA","Your freaky side hehe","Your weird side (my fav)",
    "Whenever you blow kisses","Your voice holy Your voice is my fav","Your art",
    "I love you honey mwah mwah ❤️","The way you try to hide when u get shy","The way you scrunch your nose",
    "How you remember tiny details about me","How you say my name when you're annoyed lol",
    "Your competitive side during games","How you pout (i can tell by the way u talk) when you lose",
    "How you still say \"hug me\" over call, even from far away","How you hum","Your handwriting",
    "How you still sit through a call even when you're exhausted from work","How you get excited over food",
    "Your bravery when things get hard","How honest you are with me","Your random thoughts you text me",
    "The way you say \"wait wait wait\" or \"did you know?\" before telling a story",
    "Your storytelling, even the long ones","How you always double check if I ate",
    "Your protectiveness over the people you love","How you apologize when you're wrong",
    "The kiss you always send, like it's real","The way you fall asleep on calls","Your morning texts",
    "Your soft spot for animals","How you talk to pets in baby voice","Your organized chaos",
    "How you plan surprises for me","Your terrible jokes that make me laugh anyway",
    "The way you say \"no but listen\"","How you remember our inside jokes","Your loyalty",
    "How you never give up on us","The way you style your clothing","How you dance to TikTok dances",
    "Your bad singing that I secretly love","How you take care of me when I'm sick over the phone",
    "The way you say \"take care\" every time","Your ambition","How you dream big for us",
    "Your soft heart under all the sarcasm","How you tease me but mean well",
    "Your resting face that looks mad but isn't","How you get shy over compliments",
    "Your effort in every little thing you do","The way you say my name softly",
    "How just hearing your voice fixes my whole day",
    "How you still make time for me between shifts, even exhausted","Your jealousy that you try to hide",
    "How you always choose us over pride","Your patience with my nonsense","The way you listen when I rant",
    "Your advice","How you never make me feel small","Your childhood stories",
    "How your eyes light up talking about your passions","How you save memes for me",
    "Your bad moods that still soften around me","How you never sleep angry","Your forgiveness",
    "The way you say sorry first","Your quiet strength","How you show up even when tired",
    "Your effort to understand me","The way you remember my schedule better than I do",
    "Your reminders to drink water","How you keep photos of me","Your nostalgia over small moments",
    "How you say \"remember when\"","How you still wake up at 4am and show up for work",
    "How you make your data last just to keep talking to me",
    "How you squeeze in a text on your break just so I know you're okay","Your calm during my panics",
    "How you ground me","Your silence that still comforts me",
    "How you stay on the phone with me even in silence, just so I'm not alone","Your randomness",
    "How you make ordinary days feel special","Your excitement over small wins","How proud you get of me",
    "How you defend me","How protective you are of me even from miles away","Your manners",
    "How you treat strangers kindly","Your patience with kids LOL",
    "How gentle you are with people who are struggling","Your empathy","How you cry at movies and deny it",
    "Your soft spot for sad songs","How you get quiet when you're deep in thought",
    "How you always come back to talk it out","Your communication, even when it's hard",
    "How you never give me silent treatment for long ehem","Your maturity in fights",
    "How you choose us over winning arguments","Your softness after an argument",
    "How you always check if I'm okay after","Your care in little gestures","Your thoughtfulness in gifts",
    "How you notice when something's off with me","Your intuition about my moods",
    "How you always know what to say","Your comfort food recommendations","Your generosity",
    "How you never make me feel like a burden","Your patience teaching me things",
    "How you explain things simply","Your knowledge, you know a bit of everything",
    "How curious you are about the world","Your love for learning","How you get invested in random topics",
    "Your rants about things you're passionate about","How cute you look mid-rant",
    "Your determination once you set a goal","How you never really quit on things that matter",
    "Your resilience","How you bounce back from bad days","Your optimism, even when it's hard to have",
    "How you make me believe in good things again","Your faith in us",
    "How you never doubt \"us\" even when you doubt yourself","Your vulnerability with me",
    "How you let me see you cry","Your trust in me","How safe I feel with you","Your home-like feeling",
    "How you feel like comfort and adventure at once","Your future plans that always include me",
    "How you say \"when we\" instead of \"if we\"","Your little rituals with me",
    "How you never let a day pass without saying you love me","Your everything, honestly",
    "How lucky I feel to call you mine","How you never make the distance feel like an excuse",
    "How you send me pics of your day so I feel included in it",
    "How you never end a call without saying goodnight properly",
    "How you never let the distance stop you from being present in my life",
    "How you make me feel close to you despite the miles between us",
    "How you show me around wherever you are through video call",
    "How you text \"im home\" so I don't worry",
    "How you text \"welcome home\" which makes me feel im at home with you",
    "How you make effort to learn things about where I live",
    "The way you make effort to learn about my culture and religion",
    "How open you are to adopting my culture","How you fall asleep on call just to feel like I'm there",
    "How out of a whole group, it was always you I kept talking to after everyone else logged off",
    "How during my worst week, you still showed up for me",
    "How you've never made this feel one-sided, even from a whole country away",
    "How loving you long distance taught me patience I didn't know I had",
    "How whatever it takes to get to you, I'd rather do that than not have you",
    "How I know this type of love isn't easy, but the one that lasts a lifetime",
    "How hard you make me work for u",
    "I love you, today, tomorrow, and every day after mwah mwah ❤️"
  ];